app:
  name: pandax
  version: 1.0.0
  
server:
  # debug release test
  model: release
  port: 7788
  # iothub使用的rpc端口  9000 9001 可能与minio端口冲突
  grpc-port: 9001
  cors: true
  # 数据上报 队列池
  queue-num: 1000
  # 接口限流
  rate:
    enable: true
    rate-num: 100
  db-type: mysql
  # 是否开启数据库表初始化
  isInitTable: false
  excel-dir: ./resource/excel/
  tls:
    enable: false
    key-file: ./resource/default.key
    cert-file: ./resource/default.pem
jwt:
  key: PandaX
  # 过期时间单位秒 7天
  expire-time: 604800
#数据上报并发识别任务数量限制
queue:
  enable: false
  num: 3000
redis:
  host: 101.35.247.125
  password: pandax
  port: 6379

mysql:
  host: 101.35.247.125:3306
  username: root
  password: 'pandax'
  db-name: pandax_iot
  config: charset=utf8&loc=Local&parseTime=true
# mini0
oss:
  endpoint: 127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: pandaxiot
  useSSL: false

taos:
  username: "root"
  password: "taosdata"
  host: "101.35.247.125:6041"
  database: "iot"
  config: ""

mqtt:
  broker: 101.35.247.125:1883
  qos: 1
  username: pandax
  password: pandax

casbin:
  model-path: './resource/rbac_model.conf'

gen:
  # 代码生成读取的数据库名称
  dbname: pandax_iot
  # 代码生成是使用前端代码存放位置，需要指定到src文件夹，相对路径
  frontpath: ../PandaUi/src

# 视频服务器使用的全局配置
global:
  http:
    listenaddr: :8801 # 网关地址，用于访问API
    listenaddrtls: :8443  # 用于HTTPS方式访问API的端口配置

gb28181:
  loglevel:        info
  #sip服务器地址 默认 自动适配设备网段
  sipip:          ""
  serial:         "34020000002000000001"
  realm:          "3402000000"
  password:       "pandax"
  #sip服务器端口
  port:
    sip: tcp:5060
# 萤石摄像头token
ys:
  appKey: ""
  secret: ""

log:
  # 日志等级, trace, debug, info, warn, error, fatal
  level: info
  file:
    path: ./
    name: panda_log.log
